name: build
on:
  push:
    branches: [master]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v2
      - name: Update advanced packaging tools
        run: sudo apt update
      - name: Install Ghostscript
        run: sudo apt install ghostscript
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
      - name: Install composer
        run: composer install --prefer-dist --no-interaction
      - name: Update composer
        run: composer self-update
      - name: Run tests
        run: composer test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml