name: PHP
on:
  push:
    branches: [master]
jobs:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      php-versions: ['7.1']
  name: PHP ${{ matrix.php-versions }}
  steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}
            extensions: mbstring, intl, zip, ctype, json
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --dev
      - name: Update packages
        run: composer self-update
      - name: Run tests.
        run: composer test